name: CI
on:
  push:
    branches: [master, dev]
jobs:
  deploy:
    env:
      KUBECONFIG: ~/.kube/config
      PORT: 8443
      HOST_URL: ${{ secrets.HOST_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract environment
        shell: bash
        run: echo "##[set-output name=env;]$([${GITHUB_REF##*/} == "master"] echo "prod" || echo "beta")"
        id: extract_environment

      - name: Extract Repo Name
        shell: bash
        run: echo "##[set-output name=repo;]$(echo ${GITHUB_REPOSITORY##*/})"
        id: extract_repo

      - name: Tests where docker registry is at
        shell: bash
        run: echo ${{ secrets.DOCKER_USERNAME }}/${{ steps.extract_repo.outputs.repo }}:${{ steps.extract_environment.outputs.env }}
        id: where_is_it

      - name: Tests where github registry is at
        shell: bash
        run: echo ${{ github.actor }}/${{ steps.extract_repo.outputs.repo }}:${{ steps.extract_environment.outputs.env }}
        id: where_is_it_2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ steps.extract_repo.outputs.repo }}
          tags: ${{ steps.extract_environment.outputs.env }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}/${{ steps.extract_repo.outputs.repo }}/${{ steps.extract_repo.outputs.repo }}
          tags: ${{ steps.extract_environment.outputs.env }}

      - name: Setup kubectl
        shell: bash
        run: |
          mkdir -p ${{ env.KUBECONFIG }} \
            && echo '${{ secrets.KUBECONFIG }}' > ${{ env.KUBECONFIG }}/config \
            && kubectl version
