name: CI
on:
  push:
    branches: [master, dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract Branch Name
        shell: bash
        run: echo "##[ set-output name=branch; ] [ ${GITHUB_REF##*/} == "master" ] && echo "prod" || echo "test""
        id: extract_branch

      - name: Extract Repo Name
        shell: bash
        run: echo "##[set-output name=repo;]$(echo ${GITHUB_REPOSITORY##*/})"
        id: extract_repo

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ steps.extract_repo.outputs.repo }}/${{ steps.extract_branch.outputs.branch }}
          tag_with_ref: false

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: my-org/my-repo/my-image
          tag_with_ref: true
